name: Postman API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  postman-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Postman API tests
        run: npm run test

      - name: Upload Newman HTML Report
        if: always()
        uses: actions/upload-artifact@v4 
        with:
          name: postman-report
          path: reports/newman-report.html